version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    
    ports:
      - "80:80"
      - "443:443"
    restart: always
    command: []
    entrypoint: ./prodstart.sh
    volumes:
      - ./client/letsencrypt:/root/broccwebsite/letsencrypt:rw
    


  
  server:
    env_file:
      - ./server/.env
    build:
      context: ./server
    ports:
      - "3001:3001"
    dns: 8.8.8.8
    restart: always
