version: '3'
services:
  bundle:
    env_file:
      - ./server/.env
    build:
      context: ./
      dockerfile: Dockerfile-concurrently
    ports:
      - "3000:3000"
      - "3001:3001"
    dns: 8.8.8.8
