version: '3'
services:
  client:
    build:
      context: ./client
    
    ports:
      - "80:80"
      - "443:443"
    restart: always
    
    
  
  server:
    env_file:
      - ./.env
    build:
      context: ./server
    ports:
      - "3001:3001"
    dns: 8.8.8.8
    restart: always
