name: Deploy on push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: docker-compose -f /root/broccwebsite/broccoli_website/docker-compose-prod.yml up --build -d